jdbc.url=jdbc:mysql://101.42.222.149:3306/nongxinle?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
#jdbc.url=jdbc:mysql://101.42.222.149:3306/nongxinletest?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#jdbc.url=jdbc:mysql://localhost:3306/nongxinle?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
jdbc.username=root
jdbc.password=Lpy87176693

jdbc.initialSize=5
jdbc.maxActive=30

jdbc.minPoolSize=2
jdbc.maxIdleTime=30000
jdbc.idleConnectionTestPeriod=100




external.images.path=file:///opt/tomcat/latest/app-data/images/

# 腾讯云 OCR 配置
tencentcloud.ocr.secret.id=AKIDvriMo5B4mHYbf9PRHwQgiW6SeeR2QdcO
tencentcloud.ocr.secret.key=d3HI5h8LL7j8JG3kGbjgPBnEQPAh181g
tencentcloud.ocr.region=ap-beijing

# DeepSeek API 配置
deepseek.api.key=sk-c730d09a4a4b4cf9b247e5a698d9776f
deepseek.api.url=https://api.deepseek.com/v1/chat/completions
